server:
  port: 2304

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:1023/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            exposedHeaders: 
              - Content-Disposition
              - Content-Type
              - Content-Length
      discovery:
        locator:
          enable: true
      routes:

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
        - id: ms-categoria-service
          uri: lb://ms-categoria-service
          predicates:
            - Path=/categoria/**
        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/producto/**

